### ISSUE TITLE
Missing icon for Promotion Status Plugin

### ISSUE THREAD

**Issue by nfalco79** [afonsof/jenkins-material-theme#38]
Some SVG is missing for this plugin and some glitches about it with this new thema:
![promotionstatus](https://cloud.githubusercontent.com/assets/4160180/12979430/58f806b4-d0d7-11e5-9a79-67806eac1ece.jpg)

Also the promotion page has strange background:
![promotionstatus_page](https://cloud.githubusercontent.com/assets/4160180/12979460/ad831854-d0d7-11e5-9706-837241d97bf5.jpg)

and also badges in the build history has abnormal red ball as background:
![promotionstatus_badge](https://cloud.githubusercontent.com/assets/4160180/12979475/c1380986-d0d7-11e5-9452-35d797db1efe.jpg)
- Jenkins 1.625.3
- Firefox

**Comment by afonsof** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved.

**Comment by afonsof** [comment]
@nfalco79 what's the plugin?
![image](https://cloud.githubusercontent.com/assets/805511/13555833/91cd8c54-e3a9-11e5-8416-adf3ad0448d8.png)

**Comment by nfalco79** [comment]
this one "promoted builds plugin" is the oldest plugin

**Comment by AlexanderPoleschuk** [comment]
There are actually more icons that are not shown in your theme. They exist on the page, but they are not displayed because of your strict override rules. 
The good examples that I've faced with are: Selenium Grid plugin and Allure Report plugin.
See attachments.
![3-11-2016 12-54-08 pm](https://cloud.githubusercontent.com/assets/9446141/13953338/855e4d5a-f04c-11e5-8762-b5110acc84c9.png)
![3-11-2016 1-02-24 pm](https://cloud.githubusercontent.com/assets/9446141/13953413/f8a3bf2a-f04c-11e5-86db-2d3f0c24a94a.png)

**Comment by afonsof** [comment]
Yes I know @AlexanderPoleschuk. I'm sorry, I'm trying to fix this. The global override was the only way I found to handle all the icons in the same way and not increase drastically the css size. Before that we were getting wrong sized icons in a sort of places or more than one selector to treat the same kind of icon due to jenkins plugins inconsistencies.

**Comment by afonsof** [comment]
@AlexanderPoleschuk and @nfalco79 I've just updated the theme to the version 1.2.2. No icon will be blank anymore. Unfortunately this change has increased the file size a little bit. I'll fix the problem with Material Design icons later.

**Comment by nfalco79** [comment]
Good work!

**Comment by nfalco79** [comment]
Resolved
